### PR TITLE
Implement ClientConnection

### PR DESCRIPTION
**Pull request by Quiggleson**
# Overview

Added working implementation of clientconnection.dart in client.dart. The packet logic is largely the same with a few small tweaks

# Obvious tasks

- Replaced all ``socket.writelns()`` with ``connection.sendPacket()`` in ``client.dart``
- Added ``onConnection()`` function in ``client.dart`` as the ``clientConnection.initialize()`` callback function
- Separated ``client.dart`` listening functions into ``updateGameState()`` and ``onUpdateIp()``
- Set ``_connection = connection`` in ``ClientConnection`` class so the functions that send packets work
- Updated ``Connection.initialize()`` so it will call the callback function and return ``Connection(socket)`` properly

# Decisions

- All host packets are sent with call "updateGameState". It seems the call is really only there for debug purposes anyway since the logic is taken care of on the client before the initial send and then the host just updates gamestate and tells the remaining clients to update gamestate as well.
- Add ``roomCode`` to client instance variables since it's needed in ``onConnection()``
- Decode data within ``Connection.listen()``. This stems from the fact that two packets can be received at once so the ``List<int> data`` could potentially have two packets worth of data. This means that it needs to be utf-8 decoded immediately so it can split by ``\n``. I reverted back from ``Packet.fromData()`` to ``Packet.fromJson()`` since I was more familiar with that workflow. In the future we could use a different function, but it would really just move that one ``packetMap`` line. Quite frankly I ran out of brainpower to think about this and largely focused on a working implementation of Connection. Sorry for the small rant. 
- Renamed the old classes to ``_client.dart`` and ``_host.dart`` to remember the old workflow until the full migration to the ``Connection`` class is complete

### CODE REVIEW

**Comment by Quiggleson** [comment]
Regarding the fragile order of packets on initializing ClientConnection, I think I was abusing the Connection callback function. I used to immediately send the 'join' packet upon a successful connection, but I updated it to not use the callback function and instead waited until the clientConnection was initialized to add the events and then call the function that sends the join packet.

**Comment by NEVED123** [comment]
Server Connection stuff now works! Just came up with some QQs
1. At what point do you want to get rid of _client.dart, _host.dart?
2. Right now, the ClientConnection handlers take in a Packet and a Connection instance, though this is unnecessary. If Client wishes to send a packet in their handler, the Client can simply refer to their instance of ClientConnection. Note that we aren't even using this functionality right now either. For an example of how this would look, look at Host._onJoinGame, where it refers to its own instance of ServerConnection to send the new packet to all people. Note that it still makes sense for the ServerConnection handlers to take in a Connection instance, as this represents the Connection that send the packet, and this is useful for our error handling.

**Comment by Quiggleson** [comment]
> Server Connection stuff now works! Just came up with some QQs
> 
> 1. At what point do you want to get rid of _client.dart, _host.dart?
> 2. Right now, the ClientConnection handlers take in a Packet and a Connection instance, though this is unnecessary. If Client wishes to send a packet in their handler, the Client can simply refer to their instance of ClientConnection. Note that we aren't even using this functionality right now either. For an example of how this would look, look at Host._onJoinGame, where it refers to its own instance of ServerConnection to send the new packet to all people. Note that it still makes sense for the ServerConnection handlers to take in a Connection instance, as this represents the Connection that send the packet, and this is useful for our error handling.

1. Just got rid of _client.dart and _host.dart. Mainly kept these around for reference of data flow if these started breaking
2. Agreed, we don't need connection as a parameter in ClientConnection's events since all connections are coming from one place and they can send a packet via their own instance of ClientConnection. Also agreed we should keep it on ServerConnection since they're dealing with multiple connections and it is indeed useful for debugging. I removed it from the ClientConnection related functions.

One final change then I'm satisfied with the merge: I made the onConnection callback function in ClientConnection and Connection optional so there's no need to pass a dummy function anymore.

**Comment by NEVED123** [comment]
Totally agree with these decisions. Merging

**Pull request merged**
